disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - vertical_whitespace
  - todo
  - void_return
  - identifier_name
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - type_body_length
  - large_tuple
  - line_length
  - empty_count
opt_in_rules: # some rules are only opt-in
  - empty_count

  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Demo
  - iOS
  - macOS

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
